import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'OSTAD Module 13',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar bg-gray-900 p-1 text-white flex justify-center">
         <Navbar></Navbar>
        </div>
        <main className="m-4">{children}</main>
      </body>
    </html>
  )
}
